### ISSUE TITLE
updatebot issue. Can not import a multi module maven project.

### ISSUE THREAD

**Issue by cpsburca** [jenkins-x-plugins/jx-project#411]
Hello,

I have a problem importing an existing maven project. Import fails with the issue:
```[ERROR] Failed to execute goal io.jenkins.updatebot:updatebot-maven-plugin:1.1.60:plugin (default-cli) on project platform-parent: Execution default-cli of goal io.jenkins.updatebot:updatebot-maven-plugin:1.1.60:plugin failed: Cannot invoke "org.apache.maven.model.Plugin.getVersion()" because "plugin" is null -> [Help 1]```
I don't need the updatebot, and as far I can see in the older version it was the possibility to disable it.
Can you suggest me where to dig?

**Comment by cpsburca** [comment]
@jstrachan Can you please help me here? In new version there are no option to disable updatebot and in multi module maven project it's failing.

**Comment by msvticket** [comment]
The option `--no-maven-fix` has now been added to `jx project import`
