### ISSUE TITLE
allow custom key for jx import env

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x-plugins/jx-project#438]
It would be great to be able to have different key per production env (ex: when you have one per customer) https://github.com/jenkins-x-plugins/jx-project/blob/10fa9a681fa80709009ba891b648b563330118d3/pkg/cmd/importcmd/gitops_repo.go#L63

key is set here, another param could be added and if not set fallback to the default behavior.

**Comment by msvticket** [comment]
It is not spelled out in this story what you want to have acheived.

Also it is in the wrong repository: We use a jenkins-x/jx as a central issue tracker https://github.com/jenkins-x/jx/issues/new
