### ISSUE TITLE
Developer flow for onboarding new repos

### ISSUE THREAD

**Issue by joshuasimon-taulia** [jenkins-x-plugins/jx-project#474]
I'd assume most developers should not have k8s read access to the credentials in the `jx-boot` secret. To work around this, my internal developer-facing documentation currently looks something like:

1. set up the [git credential helper](https://jenkins-x.io/v3/develop/faq/using/#how-do-i-stop-jx-asking-for-git-credentials)
2. run:
```
jx project import \
 --no-collaborator \
 --git-username=$GITHUB_USERNAME \
 --git-token=$GITHUB_PERSONAL_ACCESS_TOKEN \
 --jx \
 --no-start
 ```
3. **Would you like to add a Jenkins server?**: Choose No 
4. Choose our **custom pipeline catalog**
5. Choose the **our-org-gradle-spring** pack
6. review the files in the .lighthouse directory
7. make any desired changes
8. git add .lighthouse
9. git commit
10. git push to a feature branch
11. file a PR adding the .lighthouse pipeline folder to the main branch of the git repository

cons:
- disjointed and clunky
- developers require write access to the dev/preprod gitops cluster repo. the [cluster-repo pr logic could optionally use a fork](https://github.com/jenkins-x-plugins/jx-project/blob/2d92afac7ff887a75e719383c4ff5d151f426ddf/pkg/cmd/importcmd/source_config_pr.go#L63)
- we have previously chosen to grant our github bot PAT owner permissions over the entire organization. some folks may not be able to do this

What can we do to improve this experience for non cluster-operators?

**Comment by msvticket** [comment]
This issue will not be addressed for several reasons:  it is formulated not as an issue but rather a discussion starter. As such it would fit better in Slack. See https://jenkins-x.io/community/

Also it is in the wrong repository: We use a jenkins-x/jx as a central issue tracker https://github.com/jenkins-x/jx/issues/new

**Comment by joshuasimon-taulia** [comment]
https://kubernetes.slack.com/archives/C9MBGQJRH/p1648166888284829
